/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NoResults from "../components/NoResults/NoResults";

const BACKGROUND_COLOR = "bg-gray-100";

export default function NoResultsPage() {
  return (
    <main
      className={`flex justify-center items-center min-h-screen ${BACKGROUND_COLOR}`}
    >
      <NoResults
        title="No results found"
        description="No results found. Please try again."
        imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/2678e9ddc9eb1102f2730617dcd8e5560550e81e2f777cc6d90658cb04ec4b4d?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
      />
    </main>
  );
}
