/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import NavButton from "./NavButton";

type HeaderProps = {
  openSource: string;
};

const Header: React.FC<HeaderProps> = ({ openSource }) => {
  return (
    <header className="flex gap-5 justify-between self-end max-w-full w-[461px]">
      <Logo />
      <div className="my-auto text-xs">{openSource}</div>
      <NavButton />
    </header>
  );
};

export default Header;
