/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/16abfd10b0e9020bd12ebd293175d0083d534e5f6f2196b47de113388aa46853?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
      alt="Company logo"
      className="object-contain shrink-0 self-start mt-3.5 max-w-full bg-blend-normal aspect-[2.87] w-[109px]"
    />
  );
};

export default Logo;
