/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MainContent: React.FC = () => {
  return (
    <main className="flex flex-col mt-24 ml-32 max-md:mt-10 max-md:ml-2.5">
      <section className="text-6xl font-semibold tracking-tighter leading-none whitespace-nowrap bg-blend-normal min-h-[128px] pb-[1016px] max-md:pb-24 max-md:text-4xl">
        <h1>
          <span className="text-white text-opacity-50 max-md:text-4xl">
            Productivity.
          </span>
          <br />
          <span className="text-white max-md:text-4xl">Redesigned.</span>
        </h1>
      </section>
      <section className="mt-8 text-xl tracking-tight leading-snug bg-blend-normal h-[118px] pb-[1209px] text-white text-opacity-50 max-md:pb-24 max-md:max-w-full">
        <p>
          Next, an <strong className="font-bold text-white">all-in-one</strong>{" "}
          dashboard for notes, file storage, and finances.
        </p>
        <p>
          It brings together everything you need into a single place,
          effortless.
        </p>
        <p>
          You can manage your notes, store files, track your finances securely
        </p>
        <p>
          Effortless and efficient, it combines everything you need in one spot.
        </p>
      </section>
    </main>
  );
};

export default MainContent;
