/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NavButton: React.FC = () => {
  return (
    <div className="flex gap-1.5 items-start py-1.5 pr-1.5 pl-2 text-base tracking-tight whitespace-nowrap border border-solid bg-blend-normal bg-zinc-900 border-white border-opacity-10 min-h-[54px] rounded-[32px]">
      <button className="overflow-hidden px-4 py-3 rounded-3xl border border-solid bg-blend-normal bg-zinc-800 border-white border-opacity-10 w-[71px]">
        Login
      </button>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/02fa975a936dbe0510903e08f961e02f1f4a9c5e54b2a83e267a488769f58876?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
        alt="Navigation button"
        className="object-contain shrink-0 rounded-3xl bg-blend-normal aspect-[3.52] w-[148px]"
      />
    </div>
  );
};

export default NavButton;
