/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Sidebar from "./Sidebar";
import MainContent from "./MainContent";

const ProductivityRedesigned: React.FC = () => {
  return (
    <div className="flex flex-col items-start bg-black bg-blend-normal pb-[3344px] max-md:pb-24">
      <div className="flex gap-2">
        <div className="flex overflow-hidden relative flex-col justify-center py-0.5 w-4 aspect-square fill-neutral-800">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9b5a383d8af10a9dc1c960ba05826e9339dfc5dcf1b25edaafa84e8cdf88a3b2?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
            alt=""
            className="object-cover absolute inset-0 size-full"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ef390e93c1c4de3c578332bb33283940f80eb069a4d51ca68f1a0bedec343173?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
            alt=""
            className="object-contain w-full aspect-[1.33] fill-neutral-800"
          />
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ef390e93c1c4de3c578332bb33283940f80eb069a4d51ca68f1a0bedec343173?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
          alt=""
          className="object-contain shrink-0 my-auto w-4 aspect-[1.33] fill-neutral-800"
        />
      </div>
      <div className="flex overflow-hidden flex-col items-start px-11 pt-6 pb-10 mt-7 mr-0 w-full bg-black bg-blend-normal max-md:px-5 max-md:max-w-full">
        <div className="flex w-full max-w-[1318px] max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/83c7c7923744f6b48b462c95cc8bc24ba72cd5ca692b4268b74a57e0cf41c583?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
            alt="Decorative image"
            className="object-contain shrink-0 self-end mr-0 max-w-full rounded bg-blend-normal aspect-[4.35] mt-[785px] shadow-[0px_2px_4px_rgba(0,0,0,0.14)] w-[122px] max-md:mt-10"
          />
          <div className="flex flex-col grow shrink-0 basis-0 w-fit max-md:max-w-full">
            <div className="flex flex-col items-start self-end w-full font-semibold leading-none max-w-[1041px] text-white text-opacity-50 max-md:max-w-full">
              <Header openSource="Open source" />
              <div className="flex shrink-0 mt-6 ml-48 max-w-full h-px bg-blend-normal w-[392px] max-md:ml-2.5" />
              <div className="flex shrink-0 max-w-full h-px bg-blend-normal w-[784px]" />
            </div>
            <div className="flex overflow-hidden p-px rounded-lg border border-solid bg-blend-normal border-neutral-700 max-md:mr-2.5">
              <div className="flex flex-col grow shrink-0 bg-blend-normal basis-0 w-fit max-md:max-w-full">
                <div className="flex flex-col w-full bg-blend-normal max-md:max-w-full">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/c1d7c12c2187416c1db6532abb6a347ceaa5662b9a252919194065ae4b725835?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                    alt="Main content background"
                    className="object-contain bg-blend-normal aspect-[13.51] w-[1278px] max-md:max-w-full"
                  />
                  <div className="flex z-10 flex-wrap gap-10 mt-0 ml-2.5 w-full max-w-[1140px] max-md:max-w-full">
                    <Sidebar />
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/8279808b3ba1bfc5e852c8016af341398987a0e82ef4f0d9ccb063b7d41d2c21?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                      alt="Main content image"
                      className="object-contain grow shrink-0 self-end mt-40 bg-blend-normal aspect-[1.75] basis-0 w-fit max-md:mt-10 max-md:max-w-full"
                    />
                  </div>
                </div>
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/5c77aa85ba3019de6c55742af3140f907b8531e851e34f051b6ca37f12cb40e3?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
                alt="Decorative icon"
                className="object-contain shrink-0 self-start mt-80 rounded-3xl bg-blend-normal aspect-square w-[45px] max-md:mt-10"
              />
            </div>
            <div className="flex shrink-0 self-center max-w-full h-px bg-blend-normal w-[784px]" />
            <div className="flex shrink-0 self-center max-w-full h-px bg-blend-normal w-[392px]" />
          </div>
        </div>
        <div className="flex shrink-0 mt-36 ml-32 max-w-full h-px bg-blend-normal w-[392px] max-md:mt-10 max-md:ml-2.5" />
        <MainContent />
      </div>
    </div>
  );
};

export default ProductivityRedesigned;
