/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col pt-56 pb-3.5 bg-blend-normal min-h-[738px] max-md:hidden max-md:pt-24">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/cc0947949dc6d603c8c6bd1207365c621305c7280790199e38e586d505aa535c?placeholderIfAbsent=true&apiKey=3cf1db2ab1694ce4be6d4ee2ec473197"
        alt="Sidebar top icon"
        className="object-contain rounded-3xl bg-blend-normal aspect-[0.15] w-[45px]"
      />
      <nav className="flex flex-col py-0.5 pr-px pl-0.5 mt-28 rounded-3xl border border-solid bg-blend-normal border-neutral-700 min-h-[101px] w-[35px] max-md:mt-10">
        {[8, 9, 10].map((num) => (
          <img
            key={num}
            loading="lazy"
            src={`http://b.io/ext_${num}-`}
            alt={`Navigation icon ${num - 7}`}
            className="object-contain w-full bg-blend-normal aspect-square rounded-[50px]"
          />
        ))}
      </nav>
    </aside>
  );
};

export default Sidebar;
