import Header from "@/components/header";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark  text-2xl`}>
        <SessionProvider>
          <Header />
          <main
            className="max-w-3xl mx-auto"
          >{children}
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
